### ISSUE TITLE
AGConnectApp named [Default] already exits

### ISSUE THREAD

**Issue by Ghousepasha-ios** [HMS-Core/hms-push-serverdemo-csharp#6]
Am getting following exception.

AGConnectApp named [Default] already exits

What does it mean?

**Comment by Xuejiao-Shi** [comment]
This issue may be caused by repeated creation of AGConnectApp.
similar question for you reference, but it's in Chinese, you can translate it：https://developer.huawei.com/consumer/cn/forum/topic/0201691801128470750?fid=18

**Comment by Ghousepasha-ios** [comment]
But am creating AGConnectApp to access my account,

Please check below image.
![123 (1)](https://user-images.githubusercontent.com/2462284/179475720-be29f8ae-449d-4a53-90fc-d24bed153bb9.png)

**Comment by Xuejiao-Shi** [comment]
Can I confirm what changes you made in the project after you downloaded the demo?

**Comment by Ghousepasha-ios** [comment]
I have Just added AGConnectAdmin SDK to my solution and added AGConnectAdmin Reference.

And try to send notification from my project using above method.
![234](https://user-images.githubusercontent.com/2462284/179493673-ea220d07-4d41-4e7a-9b2d-d971494f762f.png)

**Comment by Xuejiao-Shi** [comment]
This error may be caused by the repeated creation of AGConnectApp.
![image](https://user-images.githubusercontent.com/99166105/179691979-686e33bf-40df-4447-9e39-261afb1f9dde.png)

This is the code for throwing an exception because the AGConnectApp already exists. You may have created AGConnectApp in other places besides the code in the screenshot which you provided. You can search for the create keyword to locate the fault.

**Comment by Ghousepasha-ios** [comment]
Am getting `Object reference not set to an instance of the object` exception when used below code.

`await AGConnectMessaging.DefaultInstance.SendAsync(new Message()

                 {

 

                     Notification = new Notification()

                     {

                         Title = "Test Message",

                         Body = "Detail Message",

                     },

                     Android = new AndroidConfig()

                     {

                         Notification = new AndroidNotification()

                         {

                             Title = "Notification from .NET",

                             Body = "Hello world!",

                             ClickAction = ClickAction.OpenApp()

                         }

                     },

                     Token = new List<string>() { "IQAAAACy0uRmAAAvsZe3QA42M8KS-3Dg6Dyqubcc8cTUIj-PW7tV0z82aiuXXNoNR_n_XV9HZ0BUa9VtkAi-OUNGxXN_rLYNbhgad5mgfBvdirxssQ" }

                 });`

**Comment by Ghousepasha-ios** [comment]
@Xuejiao-Shi 
Am using above code in ASP.net Webapi, 

Do i need to initialise below code some where else ?
```
var ag = AGConnectApp.Create(new AppOptions()

            {

                ClientId = "",

                ClientSecret = ""

            });
```

**Comment by Ghousepasha-ios** [comment]
@Xuejiao-Shi 
I fixed the problem by writing `AGConnectApp.Create` code in start of the application and use `DefaultInstance`.

Now am able to send notifications from my C# project.

Thanks for your valuable time and help.
